version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/apps/web"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:10"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 5

  - package-ecosystem: "composer"
    directory: "/apps/web"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:20"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "php"
    open-pull-requests-limit: 10
    groups:
      web-composer-non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "javascript"
    open-pull-requests-limit: 10
    groups:
      web-npm-non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/tests/e2e"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:40"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "e2e"
    open-pull-requests-limit: 5
    groups:
      e2e-npm-non-major:
        update-types:
          - "minor"
          - "patch"
