apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lottery.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "lottery.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  APP_ENV: {{ .Values.env.appEnv | quote }}
  APP_DEBUG: {{ .Values.env.appDebug | quote }}
  APP_URL: {{ .Values.env.appUrl | quote }}
  DB_HOST: {{ .Values.env.dbHost | quote }}
  DB_PORT: {{ .Values.env.dbPort | quote }}
  DB_DATABASE: {{ .Values.env.dbDatabase | quote }}
  DB_USERNAME: {{ .Values.env.dbUsername | quote }}
  REDIS_HOST: {{ .Values.env.redisHost | quote }}
  QUEUE_CONNECTION: {{ .Values.env.queueConnection | quote }}
  CACHE_DRIVER: {{ .Values.env.cacheDriver | quote }}
