apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lottery.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "lottery.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  APP_KEY: ""
  DB_PASSWORD: {{ .Values.env.dbPassword | quote }}
