apiVersion: v1
kind: Service
metadata:
  name: {{ include "lottery.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "lottery.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "lottery.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
