/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/campaign/current': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current campaign */
        get: operations['getCurrentCampaign'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/campaign/current/prizes': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get prizes for current campaign */
        get: operations['getCurrentCampaignPrizes'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/draws/history': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get historical draw runs */
        get: operations['getDrawHistory'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/winners': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get published winners with masked participant data */
        get: operations['getWinners'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/stats/public': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public platform statistics */
        get: operations['getPublicStats'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CampaignResponse: {
            data: components['schemas']['Campaign'];
        };
        PrizeListResponse: {
            data: components['schemas']['Prize'][];
        };
        DrawRunPaginatedResponse: {
            data: components['schemas']['DrawRun'][];
            links: components['schemas']['PaginationLinks'];
            meta: components['schemas']['PaginationMeta'];
        };
        WinnerPaginatedResponse: {
            data: components['schemas']['Winner'][];
            links: components['schemas']['PaginationLinks'];
            meta: components['schemas']['PaginationMeta'];
        };
        PublicStatsResponse: {
            data: components['schemas']['PublicStats'];
        };
        Campaign: {
            id: number;
            name: string;
            slug?: string;
            status: string;
            description?: string | null;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: date-time */
            final_draw_at: string;
        };
        Prize: {
            id: number;
            name: string;
            /** @enum {string} */
            draw_type: 'daily' | 'final';
            quantity: number;
            /** Format: float */
            value: number;
        };
        DrawRun: {
            id: number;
            campaign_id: number;
            /** @enum {string} */
            type: 'daily' | 'final';
            /** @enum {string} */
            status: 'pending' | 'running' | 'completed' | 'failed';
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            finished_at: string | null;
            winner_count: number;
        };
        Winner: {
            id: number;
            campaign_id: number;
            draw_run_id: number;
            entry_id: number;
            campaign_name?: string | null;
            prize_name?: string | null;
            winner: {
                email: string | null;
                city: string | null;
            };
            /** Format: date-time */
            published_at: string;
        };
        PublicStats: {
            entries_total: number;
            winners_total: number;
            active_campaigns: number;
        };
        PaginationLinks: {
            first: string | null;
            last: string | null;
            prev: string | null;
            next: string | null;
        };
        PaginationMeta: {
            current_page: number;
            from: number | null;
            last_page: number;
            links: components['schemas']['PaginationMetaLink'][];
            path: string;
            per_page: number;
            to: number | null;
            total: number;
        };
        PaginationMetaLink: {
            url: string | null;
            label: string;
            active: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active campaign */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CampaignResponse'];
                };
            };
            /** @description No active campaign */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentCampaignPrizes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prize list for the active campaign */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['PrizeListResponse'];
                };
            };
            /** @description No active campaign */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDrawHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated draw history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['DrawRunPaginatedResponse'];
                };
            };
        };
    };
    getWinners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated winner list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['WinnerPaginatedResponse'];
                };
            };
        };
    };
    getPublicStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public KPIs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['PublicStatsResponse'];
                };
            };
        };
    };
}
